#!/usr/bin/env bash

set -eu

OAUTH_TOKEN="${OAUTH_TOKEN:-}"

tags=()

function release_as {
    tag_name="${1}"

    release_id=$(curl --request POST \
         --silent \
         --header 'Accept: application/vnd.github.v3+json' \
         --header "Authorization: token ${OAUTH_TOKEN}" \
         --data "{\"tag_name\":\"${tag_name}\",\"name\":\"${tag_name}\"}" \
         --fail \
         'https://api.github.com/repos/imatic/docker-tools/releases' | jq '.id')

    curl --request POST \
         --header 'Accept: application/vnd.github.v3+json' \
         --header "Authorization: token ${OAUTH_TOKEN}" \
         --header 'Content-Type: application/vnd.debian.binary-package' \
         --data-binary @"build/deb/docker-tools_${tags[@]}_all.deb" \
         "https://uploads.github.com/repos/imatic/docker-tools/releases/${release_id}/assets?name=docker-tools-${tag_name}.deb"
}

function append_git_tags {
    local IFS=$'\n'
    tags+=($(git tag --list --points-at HEAD))
}

append_git_tags

if [[ ${#tags[@]} -eq 0 ]]; then
    printf "No tags found. Canceling release...\n"
    exit 0
elif [[ ${#tags[@]} -gt 1 ]]; then
    printf "Commit can have only one tag.\n" >&2
    exit 1
fi

make VERSION="${tags[@]%-*}" RELEASE="${tags[@]#*-}" debian-package

release_as "${tags[@]}"
release_as "latest"

